# Generated by Django 5.0.1 on 2024-02-14 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_realname',
            field=models.CharField(db_comment='실명', default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
