# Generated by Django 5.0.1 on 2024-01-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingr_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ingr_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pre_name', models.TextField(null=True)),
            ],
        ),
    ]
