# Generated by Django 5.0.1 on 2024-01-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_ingredient_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='med_ingr',
            field=models.ManyToManyField(to='medicines.ingredient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pre_ingr',
            field=models.ManyToManyField(to='medicines.ingredient'),
        ),
    ]
