# Generated by Django 5.0.1 on 2024-01-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_medicine_med_ingr_prescription_pre_ingr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingr_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
