# Generated by Django 5.0.1 on 2024-01-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_alter_ingredient_ingr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingr_name',
            field=models.TextField(max_length=100),
        ),
    ]
