# Generated by Django 5.0.1 on 2024-01-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_alter_ingredient_ingr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingr_name',
            field=models.TextField(),
        ),
    ]
