# Generated by Django 5.0.1 on 2024-02-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_medicine_med_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med_barcode',
            field=models.TextField(null=True),
        ),
    ]
