# Generated by Django 5.0.1 on 2024-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='used',
            name='used_nickname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
