# Generated by Django 5.0.1 on 2024-02-07 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notice_create_dttm', models.DateTimeField(auto_now_add=True)),
                ('notice_send_dttm', models.DateTimeField(null=True)),
                ('notice_read_dttm', models.DateTimeField(null=True)),
                ('notice_del_dttm', models.DateTimeField(null=True)),
                ('notice_content', models.CharField(max_length=100)),
                ('slot_lod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.slot')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
