# Generated by Django 5.0.1 on 2024-02-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_content',
            field=models.CharField(max_length=300),
        ),
    ]
