# Generated by Django 5.0.1 on 2024-01-29 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0006_alter_ingredient_ingr_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_sn', models.CharField(max_length=50, unique=True)),
                ('case_reg_dttm', models.DateTimeField(auto_now_add=True)),
                ('case_temp', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('case_humid', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('case_sensor_dttm', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot_num', models.SmallIntegerField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_num_order', models.SmallIntegerField()),
                ('book_nickname', models.CharField(max_length=50, null=True)),
                ('book_reg_dttm', models.DateTimeField(auto_now_add=True)),
                ('book_del_dttm', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.slot')),
            ],
        ),
        migrations.CreateModel(
            name='SlotLog',
            fields=[
                ('slot_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot_reg_dttm', models.DateTimeField(auto_now_add=True, null=True)),
                ('slot_del_dttm', models.DateTimeField(null=True)),
                ('slot_exp', models.DateField(null=True)),
                ('med_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.medicine')),
                ('slot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.slot')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCase',
            fields=[
                ('reg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reg_dttm', models.DateTimeField(auto_now_add=True)),
                ('reg_unreg_dttm', models.DateTimeField(null=True)),
                ('reg_nickname', models.CharField(max_length=50, null=True)),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.case')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
